baseURL = "/"
languageCode = "en-us"
title = "Dom Goodwin"
theme = "terminal"
paginate = 5

rssLimit = 20
copyright = "2024 Dom Goodwin All rights reserved"

[author]
	name = "Dom Goodwin"
	email = "dom@domgoodwin.dev"

[markup.goldmark.renderer]
unsafe= true

[params]
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Dom Goodwin"
    subtitle = "Posts, book updates and random notes"
    owner = "Dom Gooodwin"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Dom Goodwin"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "books"
        name = "Books"
        url = "/books"
      [[languages.en.menu.main]]
        identifier = "solar"
        name = "Solar"
        url = "/solar"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"